basePath: /
host: localhost:8888
info:
  contact:
    email: bodhisatanyao@gmail.com
    name: Bodhisatan
    url: https://github.com/bodhisatan
  description: This is a mall demo using Hertz and KiteX.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Mall
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 测试Description
      produces:
      - application/json
      responses: {}
      summary: 测试Summary
schemes:
- http
swagger: "2.0"
